"""End-to-end pipeline: scrape every event, parse, write one canonical parquet.

Run from the project root::

    uv run python -m alltimeathletics.pipeline

Outputs
-------
- ``data/alltime_athletics.parquet``  — one row per performance
- ``data/manifest.json``              — scrape timestamp, row counts, parser warnings

Per-event JSON for the frontend is generated by ``alltimeathletics.site`` from
this parquet; we don't write it here so the committed repo stays small.

The script exits non-zero if more than ``MAX_UNPARSED_RATIO`` of the rows fail
to parse, so a CI run will turn red rather than silently overwrite the parquet
with truncated data.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import fire
import polars as pl

from alltimeathletics.events import EVENTS
from alltimeathletics.parse import parse_page
from alltimeathletics.scrape import fetch_all

# Hard ceiling on the fraction of rows we tolerate failing to parse before the
# pipeline calls the build broken. Empirically the parser sits around 0.1 %.
MAX_UNPARSED_RATIO = 0.01

OUTPUT_PARQUET = Path("data/alltime_athletics.parquet")
OUTPUT_MANIFEST = Path("data/manifest.json")


def run(
    *,
    cache_dir: str | None = None,
    output_parquet: str = str(OUTPUT_PARQUET),
    output_manifest: str = str(OUTPUT_MANIFEST),
) -> None:
    """Scrape, parse, write parquet + manifest."""
    cache_path = Path(cache_dir) if cache_dir else None
    print(f"Fetching {len(EVENTS)} event pages...", flush=True)
    htmls = fetch_all(list(EVENTS), cache_dir=cache_path)

    rows: list[dict[str, Any]] = []
    per_event_counts: dict[str, int] = {}
    per_event_warnings: dict[str, int] = {}

    for ev in EVENTS:
        result = parse_page(htmls[ev.slug], ev)
        rows.extend(result.rows)
        per_event_counts[ev.slug] = len(result.rows)
        per_event_warnings[ev.slug] = len(result.unparsed)

    total_rows = len(rows)
    total_unparsed = sum(per_event_warnings.values())
    ratio = total_unparsed / max(1, total_rows + total_unparsed)
    print(f"Parsed {total_rows} rows; {total_unparsed} unparsed ({ratio:.4%}).", flush=True)

    if ratio > MAX_UNPARSED_RATIO:
        worst = sorted(per_event_warnings.items(), key=lambda kv: -kv[1])[:10]
        print(
            f"FAIL: parser dropped {ratio:.2%} of rows (max {MAX_UNPARSED_RATIO:.2%}).",
            file=sys.stderr,
        )
        for slug, n in worst:
            print(f"  {slug:24s}  unparsed={n}", file=sys.stderr)
        sys.exit(2)

    df = _to_dataframe(rows)
    output_parquet_path = Path(output_parquet)
    output_parquet_path.parent.mkdir(parents=True, exist_ok=True)
    df.write_parquet(output_parquet_path, compression="zstd")
    print(f"Wrote {len(df)} rows to {output_parquet_path}", flush=True)

    manifest = _build_manifest(df, per_event_counts, per_event_warnings)
    Path(output_manifest).write_text(json.dumps(manifest, indent=2, default=str))
    print(f"Wrote manifest to {output_manifest}", flush=True)


def _to_dataframe(rows: list[dict[str, Any]]) -> pl.DataFrame:
    if not rows:
        raise RuntimeError("No rows parsed")
    # Drop relay 'members' from the flat parquet (kept in per-event JSON only).
    flat = [{k: v for k, v in r.items() if k != "members"} for r in rows]

    df = pl.DataFrame(
        flat,
        schema={
            "event": pl.Utf8,
            "event_slug": pl.Utf8,
            "sex": pl.Utf8,
            "legality": pl.Utf8,
            "family": pl.Utf8,
            "section": pl.Utf8,
            "rank": pl.UInt32,
            "mark_raw": pl.Utf8,
            "mark_value": pl.Float64,
            "wind": pl.Float64,
            "name": pl.Utf8,
            "country": pl.Utf8,
            "dob": pl.Date,
            "position": pl.Utf8,
            "venue": pl.Utf8,
            "date": pl.Date,
            "source_url": pl.Utf8,
        },
        strict=False,
    )
    # Normalize country casing now that the parser tolerates lowercase typos.
    # Round wind to 1 decimal — float32 round-trips show artifacts like
    # 0.8999999761581421 in JSON otherwise.
    df = df.with_columns(
        pl.col("country").str.to_uppercase(),
        pl.col("wind").round(1),
    )
    return df


def _build_manifest(
    df: pl.DataFrame,
    per_event_counts: dict[str, int],
    per_event_warnings: dict[str, int],
) -> dict[str, Any]:
    return {
        "scraped_at": datetime.now(timezone.utc).isoformat(),
        "n_rows": int(len(df)),
        "n_events": len(per_event_counts),
        "events": [
            {
                "slug": ev.slug,
                "label": ev.label,
                "sex": ev.sex,
                "legality": ev.legality,
                "family": ev.family,
                "n_rows": per_event_counts.get(ev.slug, 0),
                "n_unparsed": per_event_warnings.get(ev.slug, 0),
                "source_url": ev.url,
            }
            for ev in EVENTS
        ],
    }


def main() -> None:  # entry point for `uv run alltimeathletics`
    fire.Fire(run)


if __name__ == "__main__":
    main()
